name: Manual Dispatch and Chaining Test

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: Version

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Extract Version from Tag
        id: get_version
        env:
          VERSION: ${{ inputs.version }}
        run: |
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

  build:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo "authenticating to aws"

  deploy:
    needs:
      - build
      - release
    strategy:
      matrix:
        target:
          - development
          - production
    uses: ./.github/workflows/deploy.yml
    with:
      version: ${{ needs.release.outputs.version }}
      environment: ${{ matrix.target }}
    secrets: inherit
